apiVersion: v1
kind: Service
metadata:
  name: Todo_app  # Name of the service
  namespace: dev  # Optional: Specify the namespace where the service will reside
spec:
  selector:
    app: nginx-pod2  # Match the labels on the pods to select the correct pods
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose inside the cluster
      targetPort: 8080  # The port the container is exposing (in the pod)
      type: clusterIPservice
  clusterIP: None  # Optional: If you want to set a specific IP or leave it as None for headless service
