apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ "TODO_APP"  }}
  labels:
    app: {{ "TODO_APP" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ "TODO_APP" }}
  template:
    metadata:
      labels:
        app: {{ "TODO_APP" }}
    spec:
      containers:
        - name: flask-todo-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST }}
